charts/buckets/charts/api/templates/deployment.yaml
charts/gameengine/templates/deployment.yaml
charts/identity-api/templates/deployment.yaml
charts/market/charts/orders/templates/deployment.yaml
charts/staticweb/templates/deployment.yaml
charts/topomojo-api/templates/deployment.yaml

Fixes mismatch between pvc and deployment resources for a few charts.

Remove '-pvc' from deployment charts

---

charts/mattermost-team-edition/Chart.yaml
charts/mattermost-team-edition/templates/deployment.yaml
charts/mattermost-team-edition/templates/ingress.yaml
charts/mattermost-team-edition/templates/service.yaml
charts/mattermost-team-edition/values.yaml

Added settings to deploy with persisted config.json.  This mounts a volume to /mattermost/config so admins can change settings from the app dashboard.
Tweaked service and ingress to use full name, so multiple instances can be deployed in the same namespace.

improve Mattermost chart

---

charts/identity/Chart.yaml
charts/identity/charts/identity-api/Chart.yaml
charts/identity/charts/identity-api/templates/deployment.yaml
charts/identity/charts/identity-api/templates/job.yaml
charts/identity/charts/identity-api/templates/serviceaccount.yaml
charts/identity/charts/identity-api/values.yaml
charts/identity/values.yaml

Support running migrations when deploying multiple replicas and/or using different connection strings (permissions) for migrations and normal operations.
- The app's Program.cs looks for an `APP_DBONLY` env variable and, if found, exits after running migrations.
- The chart deploys a Job with the app image and that env variable
- The app replicas run an initContainer that waits for the job to complete
- When job completes, app runs normally (including running migrations, but shouldn't find any not already applied)
I was pleased to find that the approach I was considering was already [fleshed out by Andrew Lock](https://andrewlock.net/deploying-asp-net-core-applications-to-kubernetes-part-7-running-database-migrations-using-jobs-and-init-containers/), especially the use of `k8s-wait-for` …

clean migrations

---

charts/gameboard/Chart.yaml
charts/gameboard/charts/gameboard-api/Chart.yaml
charts/gameboard/charts/gameboard-api/templates/configmap.yaml
charts/gameboard/charts/gameboard-ui/Chart.yaml

- Bump chart versions for `gameboard-api` and `-ui`.
- Fix gameboard-api configmap when `cacert:` value is not present.

Gameboard 3.1.0 update

---

charts/gameboard/Chart.yaml
charts/gameboard/charts/gameboard-api/Chart.yaml
charts/gameboard/charts/gameboard-api/templates/ingress.yaml
charts/gameboard/charts/gameboard-api/values.yaml
charts/gameboard/charts/gameboard-ui/Chart.yaml
charts/gameboard/charts/gameboard-ui/templates/ingress.yaml
charts/gameboard/charts/gameboard-ui/values.yaml
charts/gameboard/values.yaml
charts/identity/Chart.yaml
charts/identity/charts/identity-api/Chart.yaml
charts/identity/charts/identity-api/templates/ingress.yaml
charts/identity/charts/identity-api/values.yaml
charts/identity/charts/identity-ui/Chart.yaml
charts/identity/charts/identity-ui/templates/ingress.yaml
charts/identity/values.yaml
charts/staticweb/Chart.yaml
charts/staticweb/templates/NOTES.txt
charts/staticweb/templates/ingress.yaml
charts/staticweb/values.yaml
charts/topomojo/Chart.yaml
charts/topomojo/charts/topomojo-api/Chart.yaml
charts/topomojo/charts/topomojo-api/templates/ingress.yaml
charts/topomojo/charts/topomojo-api/values.yaml
charts/topomojo/charts/topomojo-ui/Chart.yaml
charts/topomojo/charts/topomojo-ui/templates/ingress.yaml
charts/topomojo/charts/topomojo-ui/values.yaml
charts/topomojo/values.yaml

This brings the Foundry Appliance charts (identity, topomojo, gameboard,
staticweb) up to date with the Kubernetes **networking.k8s.io/v1** API. This
is required for Kubernetes v1.22+.
`pathType` is now required for each specified Ingress path. See the
updated values.yaml for an sample config.

Update Ingress for Foundry Appliance charts

---

charts/cubespace-server/Chart.yaml
charts/cubespace-server/templates/deployment.yaml
charts/cubespace-server/values.yaml

Adds `-debug` and `-dev` boolean arguments.
`settings:` values now commented instead of providing defaults via command line arguments.

Update Cubespace Server with additional args

---

charts/code-server/.helmignore
charts/code-server/Chart.yaml
charts/code-server/templates/NOTES.txt
charts/code-server/templates/_helpers.tpl
charts/code-server/templates/deployment.yaml
charts/code-server/templates/ingress.yaml
charts/code-server/templates/pvc.yaml
charts/code-server/templates/secrets.yaml
charts/code-server/templates/service.yaml
charts/code-server/templates/serviceaccount.yaml
charts/code-server/templates/tests/test-connection.yaml
charts/code-server/values.yaml

Mirror code-server chart from https://coder.com/docs/code-server/latest/helm
This is needed because the project does not serve their chart like other Helm repositories:
https://github.com/coder/code-server/issues/2302

Mirror code-server chart

---

charts/cubespace-client/Chart.yaml
charts/cubespace-client/values.yaml
charts/cubespace-server/Chart.yaml
charts/cubespace-server/values.yaml

Updates `cubespace-[client|server]` to use publicly-available container images on Docker Hub.

Update Cubespace charts to use Docker Hub images

---

charts/gamebrain/Chart.yaml
charts/gamebrain/values.yaml

Points Gamebrain chart to use newly released Docker Hub image:
https://hub.docker.com/r/cmusei/gamebrain

Update Gamebrain to use public Docker image

---

charts/blueprint/charts/blueprint-ui/templates/secret.yaml
charts/gallery/charts/gallery-ui/templates/secret.yaml

Gallery.UI and Blueprint.UI both have supposed support for the `APP_BASEHREF` environment variable. This patch imports the env configuration block as a secret to enable this feature as supported by other charts in this repository.

Add support for env in Gallery and Blueprint UI modules

---

charts/mkdocs-material/Chart.yaml
charts/mkdocs-material/templates/configmap-entry.yaml
charts/mkdocs-material/templates/configmap.yaml
charts/mkdocs-material/templates/cronjob.yaml
charts/mkdocs-material/templates/deployment.yaml
charts/mkdocs-material/values.yaml

This PR adds some improvements for the handling of mkdocs materials when using git as a source for the docs. The changes are summarized as follows:
1. Allows the use of the existing persistent volume claim for both the cronjob and the init containers of the deployment when running using git
2. Supports overriding the site_url of the mkdocs.yml file when the deployment is served at a different host than the git repo specifies in the site_url field
3. Supports overriding the path that nginx uses to redirect traffic to the static website to match the value specified in site_dir rather than the default value of "site"
4. Supports providing git credentials as a secret in the format used by the git store credential helper
Note:
Because this PR configures git to use the store git credential …

Added additional support for git documentation sources

---

charts/mkdocs-material/Chart.yaml
charts/mkdocs-material/templates/configmap-entry.yaml
charts/mkdocs-material/templates/configmap.yaml
charts/mkdocs-material/templates/cronjob.yaml
charts/mkdocs-material/templates/deployment.yaml

This PR adds a conditional check on the git repo so that mkdocs only builds if something has changed since the last poll. I also changed new builds so that they are done "asynchronously." This is achieved by serving the docs via a symbolic link to a build directory. The link stays in place during a new build and swaps over at the end so that downtime and impact on the doc site are minimized regardless of how long the build takes. Build times of more than one minute had been causing the site to become unresponsive when docs disappeared.

Add conditional check for doc build and minimize build impact on doc site.

---

charts/alloy/Chart.yaml
charts/alloy/charts/alloy-api/templates/deployment.yaml
charts/alloy/charts/alloy-api/values.yaml
charts/alloy/values.yaml
charts/blueprint/Chart.yaml
charts/blueprint/charts/blueprint-api/templates/deployment.yaml
charts/blueprint/charts/blueprint-api/values.yaml
charts/blueprint/values.yaml
charts/caster/Chart.yaml
charts/caster/charts/caster-api/templates/deployment.yaml
charts/caster/charts/caster-api/values.yaml
charts/caster/values.yaml
charts/cite/Chart.yaml
charts/cite/charts/cite-api/templates/deployment.yaml
charts/cite/charts/cite-api/values.yaml
charts/cite/values.yaml
charts/gallery/Chart.yaml
charts/gallery/charts/gallery-api/templates/deployment.yaml
charts/gallery/charts/gallery-api/values.yaml
charts/gallery/values.yaml
charts/player/Chart.yaml
charts/player/charts/player-api/templates/deployment.yaml
charts/player/charts/player-api/values.yaml
charts/player/charts/vm-api/templates/deployment.yaml
charts/player/charts/vm-api/values.yaml
charts/player/values.yaml
charts/steamfitter/Chart.yaml
charts/steamfitter/charts/steamfitter-api/templates/deployment.yaml
charts/steamfitter/charts/steamfitter-api/values.yaml
charts/steamfitter/values.yaml

This PR adds the ability to specify additional environment variables to be added via existing k8s secrets the following crucible apps:
- Caster api
- Alloy api
- BP api
- Cite api
- Steamfitter api
- Gallery api
- Player api
- VM api
Here is an example of what the values file would look like for blueprint api to do this:
```
blueprint-api:
image:
tag: "1.4.3"
existingSecret: "bp-secret"
```
The corresponding secret in the cluster might look like this:
```
apiVersion: v1
kind: Secret
metadata:
name: bp-secret
type: Opaque
stringData:
ConnectionStrings__PostgreSQL: 'Server=postgres;Port=5432;Database=blueprint_db;Username=blueprint_dbo;Password=foo;SSL Mode=Prefer;Trust Server Certificate=true;'
ResourceOwnerAuthorization__Password: 'bar'
```

Add ability to specify k8s secrets as extra environment variables for selected crucible apps

---

charts/gameboard/Chart.yaml
charts/gameboard/charts/gameboard-api/Chart.yaml
charts/gameboard/charts/gameboard-api/templates/deployment.yaml
charts/gameboard/charts/gameboard-api/values.yaml
charts/gameboard/values.yaml

This PR adds the ability to specify additional environment variables to be added via existing k8s secrets to gameboard. It follows the same approach that was used in [a previous merge request](https://github.com/cmu-sei/helm-charts/pull/75)
Here is an example of what the values file would look like:
``` 
gameboard-api:
existingSecret: "gameboard-secret"
```
The corresponding secret in the cluster might look like this:
```
apiVersion: v1
kind: Secret
metadata:
name: gameboard-secret
type: Opaque
stringData:
ConnectionStrings__PostgreSQL: 'Server=postgres;Port=5432;Database=gameboard_db;Username=gameboard_dbo;Password=foo;SSL Mode=Prefer;Trust Server Certificate=true;'
ResourceOwnerAuthorization__Password: 'bar'
```

Add ability to specify k8s secrets as extra environment variables for Gameboard

---

charts/mkdocs-material/Chart.yaml
charts/mkdocs-material/templates/_helpers.tpl
charts/mkdocs-material/templates/configmap-cacerts.yaml
charts/mkdocs-material/templates/configmap-entry.yaml
charts/mkdocs-material/templates/cronjob.yaml
charts/mkdocs-material/templates/deployment.yaml
charts/mkdocs-material/values.yaml

This PR fixes a bug in the current mkdocs helm chart where the name of the volumeMounts only matched the name of the corresponding volumes if the helm release happened to be named the same as the chart.
In addition to that it adds these features:
- pvc volumes can be used without a suffix subPath or with a custom suffix subPath
- trusted cacerts can be added to the git-pull container using the certificateMap property as in other crucible helm charts
- the git-pull script has been changed to use environment variables for conditional checks rather than using go templating variables within the script

Correct bug with volume names and add options for pvc prefix and cacert secrets

---

charts/topomojo/Chart.yaml
charts/topomojo/charts/topomojo-api/Chart.yaml
charts/topomojo/charts/topomojo-api/templates/console-ingress.yaml
charts/topomojo/charts/topomojo-api/values.yaml
charts/topomojo/values.yaml

The PR adds an optional ingress to topomojo for websocket connections to vmware consoles. It is patterned after a similar capability in the player vm api helm chart.

Add vm-consoles ingress option to topomojo

---

charts/cite/Chart.yaml
charts/cite/charts/cite-api/templates/deployment.yaml
charts/cite/charts/cite-api/values.yaml
charts/cite/values.yaml

The PR adds the ability to add trusted cacerts to the cite-api pod container as other crucible apps do via the certificateMap value.

Cite add ability to inject custom trusted cacerts

---

charts/gameboard/Chart.yaml
charts/gameboard/charts/gameboard-api/Chart.yaml
charts/gameboard/charts/gameboard-api/templates/deployment.yaml
charts/gameboard/charts/gameboard-api/templates/ingress.yaml
charts/gameboard/charts/gameboard-api/templates/secret.yaml
charts/gameboard/charts/gameboard-ui/Chart.yaml
charts/gameboard/charts/gameboard-ui/templates/configmap.yaml
charts/gameboard/charts/gameboard-ui/templates/ingress.yaml
charts/gameboard/charts/gameboard-ui/values.yaml
charts/gameboard/values.yaml

Similar to #86 and #87, this PR gives the same treatment to the Gameboard chart. This allows for improved values templating when Gameboard is included in umbrella Helm charts.

[gameboard] Add settingsYaml: and tpl templating

---

charts/mkdocs-material/Chart.yaml
charts/mkdocs-material/templates/configmap.yaml
charts/mkdocs-material/templates/deployment.yaml
charts/mkdocs-material/templates/ingress.yaml

Similar to #87 and #88, this PR adds value templating via `tpl` to the mkdocs-material chart. This makes it easier template values like domain names, Helm releases, and namespaces.

[mkdocs-material] Add values templating

---

charts/lrsql/.helmignore
charts/lrsql/Chart.yaml
charts/lrsql/examples/crucible-lrs.values.yaml
charts/lrsql/templates/NOTES.txt
charts/lrsql/templates/_helpers.tpl
charts/lrsql/templates/configmap-env.yaml
charts/lrsql/templates/configmap-templates.yaml
charts/lrsql/templates/deployment.yaml
charts/lrsql/templates/ingress.yaml
charts/lrsql/templates/pvc.yaml
charts/lrsql/templates/service.yaml
charts/lrsql/templates/serviceaccount.yaml
charts/lrsql/values.yaml

This PR adds a helm chart for the [Yet Analytics SQL LRS](https://github.com/yetanalytics/lrsql) using the hosted docker container for that open source tool. The chart supports all of the features that are available via the current version of the docker container, currently v0.8.4, and uses [environment variables](https://github.com/yetanalytics/lrsql/blob/main/doc/env_vars.md) for configuration as opposed to a [config file](https://github.com/yetanalytics/lrsql/blob/main/resources/lrsql/config/lrsql.json.example).
I tested this by using a [local chart](https://gitlab.imcite.net/imcite/imcite/-/blob/phlprod-start/argocd/charts/lrsql/Chart.yaml?ref_type=heads) in both phlstaging and phlprod.

Add Yet Analytics SQL LRS helm chart

---

charts/alloy/charts/alloy-api/Chart.yaml
charts/alloy/charts/alloy-api/templates/deployment.yaml
charts/alloy/charts/alloy-api/templates/service.yaml
charts/alloy/charts/alloy-api/values.yaml
charts/caster/charts/caster-api/Chart.yaml
charts/caster/charts/caster-api/templates/_helpers.tpl
charts/caster/charts/caster-api/templates/configmap.yaml
charts/caster/charts/caster-api/templates/deployment.yaml
charts/caster/charts/caster-api/templates/scripts/terraform-installation.tpl
charts/caster/charts/caster-api/templates/scripts/vol-permissions.tpl
charts/caster/charts/caster-api/templates/service.yaml
charts/caster/charts/caster-api/values.yaml
charts/player/charts/player-api/Chart.yaml
charts/player/charts/player-api/templates/_helpers.tpl
charts/player/charts/player-api/templates/configmap.yaml
charts/player/charts/player-api/templates/deployment.yaml
charts/player/charts/player-api/templates/scripts/vol-permissions.tpl
charts/player/charts/player-api/templates/service.yaml
charts/player/charts/player-api/values.yaml
charts/player/charts/vm-api/Chart.yaml
charts/player/charts/vm-api/templates/deployment.yaml
charts/player/charts/vm-api/templates/service.yaml
charts/player/charts/vm-api/values.yaml
charts/steamfitter/charts/steamfitter-api/Chart.yaml
charts/steamfitter/charts/steamfitter-api/templates/deployment.yaml
charts/steamfitter/charts/steamfitter-api/templates/service.yaml
charts/steamfitter/charts/steamfitter-api/values.yaml

Adds support for the latest versions of the crucible exercise apps that use a non-root user in their images by default.
- Updates containerPort to 8080
- Updates support for trusting certificates
- Removes call to `update_ca_certificates` as it can only be run as root
- Adds `SSL_CERT_DIR` env var when Values.certificateMap is specified
- Updates file system permissions for local volume mounts
- Adds init containers to Player.Api and Caster.Api that runs as root to update file ownership to the app user
- **POTENTIAL BREAKING CHANGE**: Operators may have to manually change NFS permissions for any mounted NFS volumes
- Moves Caster terraform installation script to an init container

Adds rootless container support to crucible exercise apps

---

charts/mkdocs-material/Chart.yaml
charts/mkdocs-material/templates/cronjob.yaml

If the git CronJob for mkdocs-material stalls (when it can't load a Secret, for example), the cluster will continually create new jobs.
This fixes the problem by only allowing a single CronJob at a time.

[mkdocs-material] Forbid concurrent CronJobs

---

charts/alloy/Chart.yaml
charts/alloy/values.yaml
charts/blueprint/values.yaml
charts/caster/Chart.yaml
charts/caster/charts/caster-api/Chart.yaml
charts/caster/charts/caster-ui/Chart.yaml
charts/caster/values.yaml
charts/cite/Chart.yaml
charts/cite/values.yaml
charts/gallery/Chart.yaml
charts/gallery/values.yaml
charts/gameboard/Chart.yaml
charts/gameboard/charts/gameboard-api/Chart.yaml
charts/gameboard/charts/gameboard-ui/Chart.yaml

This updates the appVersion values for all of the Crucible apps to the latest published versions. We have been behind in keeping the 'image.tag' values up to date, and the idea with this change is that we can apply CI to this process down the road as we release new versions of Crucible apps.
This change does not impact users who have custom 'image.tag' values in their own deployments. It just makes the default values for each app more current.

Remove 'image.tag' values in favor of Chart.yaml appVersion

---

charts/topomojo/Chart.yaml
charts/topomojo/charts/topomojo-api/Chart.yaml
charts/topomojo/charts/topomojo-api/templates/deployment.yaml

Apologies, but there was an indentation problem in my previous PR that was treated as only a warning by helm, but as an error by argo. Previously,  line 51 of the api deployment was off by two spaces. I fixed this by changing the indentation style for the init container section to match that of the containers section. 
I verified it by installing a version of this chart via helm that printing out the env in the init container and I do see the SKIP_VOL_PERMISSIONS set now where it was not before. Also, I see that the old version printed a warning I had not noticed, which is no longer the case.
``` 
mpriest@mac-parrotapfel topotest % helm install -n imcite helm-mojo ~/helm-repo/helm-charts/charts/topomojo -f values.yaml
W0904 14:09:42.186830   81807 warnings.go:70] unknown field …
```

[topomojo] initcontainer bugfix

---

charts/mkdocs-material/Chart.yaml
charts/mkdocs-material/templates/_helpers.tpl
charts/mkdocs-material/templates/configmap-entry.yaml
charts/mkdocs-material/templates/configmap-macro-vars.yaml
charts/mkdocs-material/templates/cronjob.yaml
charts/mkdocs-material/templates/deployment.yaml
charts/mkdocs-material/values.yaml

This PR adds support for the [mkdocs-macros-plugin](https://mkdocs-macros-plugin.readthedocs.io/en/latest/).
The template supports the use of optional [external yaml values files](https://mkdocs-macros-plugin.readthedocs.io/en/latest/advanced/#including-external-yaml-files) to be included via a ConfigMap mounted to the pod that builds mkdocs. As explained in detail in a comment in the values.yaml file, this allows docs to define local default values that can be used while testing doc changes locally, which will be overwritten by the external yaml files (which support embedded templating) when deployed.
There is also a consolidation of the git-pull and mkdocs-build container specs that are shared between the deployment and the cronjob to reduce maintenance [as per …

[mkdocs-material] Add option for installing the mkdocs-macros-plugin.

---

charts/mkdocs-material/Chart.yaml
charts/mkdocs-material/templates/cronjob.yaml

Fixing the name of the cronjob and it's labels to be consistent with the other templates.

[mkdocs-material] The name of the cronjob needs to be the full release name including the chart to avoid conflicts

---

charts/mkdocs-material/Chart.yaml
charts/mkdocs-material/templates/_helpers.tpl
charts/osticket/Chart.yaml
charts/osticket/charts/mysql/values.yaml

Updates Docker image tags in the mkdocs-material and osticket charts to push to the bitnamilegacy Docker Hub organization.

[mkdocs-material, osticket] Update Docker image locations to bitnamilegacy organization

---

charts/gameboard/Chart.yaml
charts/gameboard/charts/gameboard-api/Chart.yaml
charts/gameboard/charts/gameboard-api/values.yaml
charts/gameboard/charts/gameboard-ui/Chart.yaml
charts/gameboard/charts/gameboard-ui/values.yaml
charts/gameboard/values.yaml
charts/topomojo/Chart.yaml
charts/topomojo/charts/topomojo-api/Chart.yaml
charts/topomojo/charts/topomojo-api/values.yaml
charts/topomojo/charts/topomojo-ui/Chart.yaml
charts/topomojo/charts/topomojo-ui/values.yaml
charts/topomojo/values.yaml

- Updates GB to 3.35.0, TM to 2.5.0
- Adds default settings hints for both in API charts
- Added a missing empty dict literal for `settingsYaml` in the topo UI chart

GB/TM app version/settings updates (IDP role assignment)
