charts/buckets/Chart.yaml, charts/buckets/charts/api/Chart.yaml, charts/gameengine/Chart.yaml, charts/identity-api/Chart.yaml, charts/market/Chart.yaml, charts/market/charts/orders/Chart.yaml, charts/staticweb/Chart.yaml, charts/topomojo-api/Chart.yaml
=> Increment versions for pvc-fix charts

charts/alloy/Chart.yaml, charts/alloy/charts/alloy-api/templates/deployment.yaml, charts/alloy/charts/alloy-api/values.yaml, charts/caster/Chart.yaml, charts/caster/charts/caster-api/templates/deployment.yaml, charts/player/Chart.yaml, charts/player/charts/player-api/templates/deployment.yaml, charts/player/charts/player-api/templates/pvc.yaml, charts/player/charts/player-api/values.yaml, charts/player/charts/vm-api/templates/deployment.yaml, charts/player/charts/vm-api/values.yaml, charts/player/charts/vm-ui/values.yaml, charts/player/values.yaml, charts/steamfitter/Chart.yaml, charts/steamfitter/charts/steamfitter-api/templates/deployment.yaml, charts/steamfitter/charts/steamfitter-api/values.yaml
- Adds `live` and `ready` probes to APIs
- Adds volume for Player file upload feature
=> update charts to contain health endpoints

charts/gameboard/Chart.yaml, charts/gameboard/charts/gameboard-api/Chart.yaml, charts/gameboard/charts/gameboard-api/templates/deployment.yaml, charts/gameboard/values.yaml, charts/staticweb/Chart.yaml, charts/staticweb/README.md, charts/staticweb/templates/configmap.yaml, charts/staticweb/templates/deployment.yaml, charts/staticweb/values.yaml, charts/topomojo/Chart.yaml, charts/topomojo/charts/topomojo-api/Chart.yaml, charts/topomojo/charts/topomojo-api/templates/configmap.yaml, charts/topomojo/charts/topomojo-api/templates/deployment.yaml, charts/topomojo/values.yaml
Adds custom CA certificate option (`cacert:`) to gameboard-api, staticweb, and topomojo-api.
=> Adds cacert: option

charts/gametracker/Chart.yaml, charts/gametracker/charts/gametracker-api/Chart.yaml, charts/gametracker/charts/gametracker-api/templates/configmap.yaml, charts/gametracker/charts/gametracker-api/templates/deployment.yaml, charts/gametracker/charts/gametracker-ui/Chart.yaml
Updates the custom CA certificate start script with the new Gameboard.Api.dll filename.
=> Update gametracker-api start.sh with new .dll

charts/player/charts/player-api/templates/deployment.yaml
- moved check for certificateMap down so other volumes still get created/mounted
=> fix player storage

charts/mkdocs-material/.helmignore, charts/mkdocs-material/Chart.yaml, charts/mkdocs-material/README.md, charts/mkdocs-material/templates/NOTES.txt, charts/mkdocs-material/templates/_helpers.tpl, charts/mkdocs-material/templates/configmap-entry.yaml, charts/mkdocs-material/templates/configmap-files.yaml, charts/mkdocs-material/templates/configmap.yaml, charts/mkdocs-material/templates/cronjob.yaml, charts/mkdocs-material/templates/deployment.yaml, charts/mkdocs-material/templates/hpa.yaml, charts/mkdocs-material/templates/ingress.yaml, charts/mkdocs-material/templates/pvc.yaml, charts/mkdocs-material/templates/service.yaml, charts/mkdocs-material/templates/serviceaccount.yaml, charts/mkdocs-material/templates/tests/test-connection.yaml, charts/mkdocs-material/values.yaml
Adds Material for MkDocs chart (similar to staticweb)
https://squidfunk.github.io/mkdocs-material/
=> Material for MkDocs chart

charts/cubespace-client/.helmignore, charts/cubespace-client/Chart.yaml, charts/cubespace-client/templates/NOTES.txt, charts/cubespace-client/templates/_helpers.tpl, charts/cubespace-client/templates/deployment.yaml, charts/cubespace-client/templates/hpa.yaml, charts/cubespace-client/templates/ingress.yaml, charts/cubespace-client/templates/service.yaml, charts/cubespace-client/templates/serviceaccount.yaml, charts/cubespace-client/templates/tests/test-connection.yaml, charts/cubespace-client/values.yaml, charts/cubespace-server/.helmignore, charts/cubespace-server/Chart.yaml, charts/cubespace-server/templates/NOTES.txt, charts/cubespace-server/templates/_helpers.tpl, charts/cubespace-server/templates/deployment.yaml, charts/cubespace-server/templates/hpa.yaml, charts/cubespace-server/templates/ingress.yaml, charts/cubespace-server/templates/service.yaml, charts/cubespace-server/templates/serviceaccount.yaml, charts/cubespace-server/templates/tests/test-connection.yaml, charts/cubespace-server/values.yaml
Adds Cubespace game charts for client and server apps
Container images are private for now, but will be published to Docker Hub in early 2023.
=> Add cubespace charts

charts/gamebrain/.helmignore, charts/gamebrain/Chart.yaml, charts/gamebrain/templates/NOTES.txt, charts/gamebrain/templates/_helpers.tpl, charts/gamebrain/templates/configmap.yaml, charts/gamebrain/templates/deployment.yaml, charts/gamebrain/templates/hpa.yaml, charts/gamebrain/templates/ingress.yaml, charts/gamebrain/templates/service.yaml, charts/gamebrain/templates/serviceaccount.yaml, charts/gamebrain/templates/tests/test-connection.yaml, charts/gamebrain/values.yaml
Gamebrain data service for Cubespace video game
Container image is currently private but will be published on Docker Hub in early 2023.
=> Add Gamebrain chart

charts/cubespace-client/Chart.yaml, charts/cubespace-server/Chart.yaml, charts/cubespace-server/templates/deployment.yaml, charts/cubespace-server/values.yaml
Increment app versions for both Cubespace charts
=> Add clientID command line param to cubespace-server

charts/cubescore/.helmignore, charts/cubescore/Chart.yaml, charts/cubescore/templates/NOTES.txt, charts/cubescore/templates/_helpers.tpl, charts/cubescore/templates/configmap.yaml, charts/cubescore/templates/deployment.yaml, charts/cubescore/templates/hpa.yaml, charts/cubescore/templates/ingress.yaml, charts/cubescore/templates/service.yaml, charts/cubescore/templates/serviceaccount.yaml, charts/cubescore/templates/tests/test-connection.yaml, charts/cubescore/values.yaml
=> Cubescore chart

charts/gameboard/Chart.yaml, charts/gameboard/charts/gameboard-api/Chart.yaml, charts/gameboard/charts/gameboard-api/templates/deployment.yaml, charts/gameboard/charts/gameboard-ui/Chart.yaml
Adds a volume mount to the Gameboard API chart. This volume mount will support persistent storage of files uploaded to support tickets.
=> Adds support files volume mount

charts/mattermost-team-edition/Chart.yaml, charts/mattermost-team-edition/templates/deployment.yaml
Update MM deployment to a rolling update strategy to match the latest official MM chart: https://github.com/mattermost/mattermost-helm/blob/master/charts/mattermost-team-edition/values.yaml#L17
=> Change MM to RollingUpdate

charts/topomojo/Chart.yaml, charts/topomojo/charts/topomojo-api/Chart.yaml, charts/topomojo/charts/topomojo-api/templates/deployment.yaml, charts/topomojo/charts/topomojo-api/values.yaml
Adds readiness probe to topomojo api helm chart and values file.
=> Adds topomojo readiness probe

charts/webmail/charts/roundcube/templates/ingress.yaml
Upload file size limit for nginx
=> Update ingress.yaml for webmail

charts/caster/Chart.yaml, charts/caster/charts/caster-api/Chart.yaml, charts/caster/charts/caster-api/templates/deployment.yaml, charts/caster/charts/caster-api/templates/statefulset.yaml, charts/caster/charts/caster-ui/Chart.yaml, charts/player/Chart.yaml, charts/player/charts/player-api/Chart.yaml, charts/player/charts/player-api/templates/deployment.yaml, charts/player/charts/player-api/templates/statefulset.yaml, charts/player/charts/player-ui/Chart.yaml, charts/player/charts/vm-api/Chart.yaml, charts/player/charts/vm-api/templates/deployment.yaml, charts/steamfitter/Chart.yaml, charts/steamfitter/charts/steamfitter-api/templates/deployment.yaml, charts/steamfitter/charts/steamfitter-ui/Chart.yaml
- Adds startupProbe to Crucible Apis
- Updates crucible versions.
=> adds startupProbe to crucible APIs

charts/mkdocs-material/Chart.yaml, charts/mkdocs-material/templates/configmap-entry.yaml
Reset before pull to remove any changes to mkdocs.yaml based on the new script. This should also cleanup any random unexpected changes within reason.
=> Fix bug where the changes to mkdocs.yaml cause git pull to fail

charts/topomojo/Chart.yaml, charts/topomojo/charts/topomojo-api/Chart.yaml, charts/topomojo/charts/topomojo-api/templates/deployment.yaml, charts/topomojo/charts/topomojo-ui/Chart.yaml
Changes the location of the customStart mount to `/home/app/start` since the TopoMojo Docker container no longer runs as root.
=> Change TopoMojo customStart mount directory

charts/player/charts/player-api/Chart.yaml, charts/player/charts/player-api/values.yaml, charts/player/values.yaml
Removing old, defaulted permissions
=> remove old permissions

charts/mkdocs-material/Chart.yaml
Upgrade mkdocs-material appVersion to 9.6.12
=> Upgrade to mkdocs-material 9.6.12

charts/alloy/Chart.yaml, charts/alloy/charts/alloy-api/Chart.yaml, charts/alloy/charts/alloy-ui/Chart.yaml, charts/player/Chart.yaml, charts/player/charts/vm-ui/Chart.yaml
Bumping subchart values for alloy and player for a few subcharts that are behind and we are setting image tags in imcite.
=> [alloy, player] Bump appVersion values to latest releases

charts/gameboard/Chart.yaml, charts/gameboard/charts/gameboard-api/Chart.yaml, charts/gameboard/charts/gameboard-ui/Chart.yaml
Update GBAPI version and corresponding chart versions.
=> Update Gameboard API to 3.34.3
